---
github_directory: github.com/samuelclay/newsblur
git_web_repo: ssh://git@{{ github_directory }}
git_secrets_repo: ssh://git@github.com/samuelclay/newsblur-secrets
git_branch: date-filter

create_user: nb
local_key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
copy_local_key: "{{ lookup('file', '/srv/secrets-newsblur/keys/docker.key.pub') }}"
postgres_user: "{{ lookup('ini', 'postgres_user section=admin file=/srv/secrets-newsblur/configs/postgres_auth.ini') }}"
postgres_password: "{{ lookup('ini', 'postgres_password section=admin file=/srv/secrets-newsblur/configs/postgres_auth.ini') }}"
mongodb_keyfile: "{{ lookup('file', '/srv/secrets-newsblur/keys/mongodb_keyfile.key') }}"
mongodb_username: "{{ lookup('ini', 'mongodb_username section=admin file=/srv/secrets-newsblur/configs/mongodb_auth.ini') }}"
mongodb_password: "{{ lookup('ini', 'mongodb_password section=admin file=/srv/secrets-newsblur/configs/mongodb_auth.ini') }}"
sentry_web_release_webhook: "{{ lookup('ini', 'web_release_webhook section=sentry file=/srv/secrets-newsblur/configs/sentry.ini') }}"
sentry_task_release_webhook: "{{ lookup('ini', 'task_release_webhook section=sentry file=/srv/secrets-newsblur/configs/sentry.ini') }}"
sentry_monitor_release_webhook: "{{ lookup('ini', 'monitor_release_webhook section=sentry file=/srv/secrets-newsblur/configs/sentry.ini') }}"
sentry_node_release_webhook: "{{ lookup('ini', 'node_release_webhook section=sentry file=/srv/secrets-newsblur/configs/sentry.ini') }}"

sys_packages:
  [
    "git",
    "python3",
    "python3-dev",
    "zsh",
    "openssl",
    "libssl-dev",
    "libssl-doc",
    "build-essential",
    "htop",
  ]
grafana_password: "{{ lookup('ini', 'grafana_password section=grafana file=/srv/secrets-newsblur/configs/grafana.ini') }}"
