---
# defaults file for docker-ce-ansible-role

docker_state: present

docker_cleanup_packages_EL:
  - {package: "docker"}
  - {package: "docker-common"}
  - {package: "docker-client"}
  - {package: "docker-engine"}

docker_cleanup_packages_Ubuntu:
  - {package: "docker.io"}
  - {package: "docker-engine"}
  - {package: "containerd"}

docker_prerequisite_packages_EL:
  - {package: "python-docker"}

docker_prerequisite_packages_Ubuntu:
  - {package: "apt-transport-https"}
  - {package: "ca-certificates"}
  - {package: "curl"}
  - {package: "software-properties-common"}

docker_prerequisite_packages_Ubuntu_1404:
  - {package: "linux-image-extra-{{ ansible_kernel }}"}
  - {package: "linux-image-extra-virtual"}
