---
- name: Copy app secrets
  copy:
    src: /srv/secrets-newsblur/settings/docker_settings.py
    dest: /srv/newsblur/newsblur_web/local_settings.py
  register: app_changed

- name: Add SERVER_NAME to app secrets
  lineinfile:
    path: /srv/newsblur/newsblur_web/local_settings.py
    line: 'SERVER_NAME = "{{ inventory_hostname }}"'

- name: Start monitor docker container
  become: yes
  docker_container:
    name: monitor
    image: newsblur/flask_monitor
    pull: yes
    env:
      DOCKERBUILD: "True"
    state: started
    command: bash -c "python /srv/newsblur/flask_monitor/db_monitor.py"
    ports:
      - 5000:5000
    restart_policy: unless-stopped
    volumes:
      - /srv/newsblur:/srv/newsblur

- name: Register monitor in consul
  tags: consul
  become: yes
  template:
    src: consul_service.json
    dest: /etc/consul.d/monitor.json
  notify:
    - reload consul
