---
- name: Copy common secrets
  copy:
    src: /srv/secrets-newsblur/settings/common_settings.py
    dest: /srv/newsblur/newsblur_web/local_settings.py
  register: app_changed

- name: Copy app env
  copy:
    src: /srv/secrets-newsblur/settings/app_env.py
    dest: /srv/newsblur/newsblur_web/app_env.py
  register: app_changed

- name: Add SERVER_NAME to app env
  lineinfile:
    path: /srv/newsblur/newsblur_web/app_env.py
    line: 'SERVER_NAME = "{{ inventory_hostname }}"'
  
- name: Start monitor docker container
  become: yes
  docker_container:
    name: monitor
    image: newsblur/newsblur_monitor:latest
    pull: yes
    state: started
    command: bash -c "python /srv/newsblur/flask_monitor/db_monitor.py"
    hostname: "{{ inventory_hostname }}"
    restart_policy: unless-stopped
    container_default_behavior: no_defaults
    volumes:
      - /srv/newsblur:/srv/newsblur
    networks_cli_compatible: yes
    network_mode: default
    networks:
      - name: newsblurnet
    ports:
      - "5579:5579"

- name: Restart monitor
  become: yes
  shell:
    cmd: docker restart monitor
