---
- name: Start Elasticsearch Docker container
  become: yes
  docker_container:
    name: elasticsearch
    image: elasticsearch:1.7.6
    state: started
    ports:
      - '9200:9200'
    restart_policy: unless-stopped
    volumes:
      - /srv/newsblur/docker/volumes/elasticsearch:/usr/share/elasticsearch/data

- name: Register elasticsearch in consul
  tags: consul
  become: yes
  template:
    src: consul_service.json
    dest: /etc/consul.d/elasticsearch.json
  notify:
    - reload consul

- name: Add sanity checkers cronjob for disk usage
  become: yes
  cron:
    name: disk_usage_sanity_checker
    user: root
    cron_file: /etc/cron.hourly/disk_usage_sanity_checker
    job: docker pull newsblur/newsblur_python3:latest;
      docker run --rm -it
      OUTPUT=$(eval sudo df / | head -n 2 |  tail -1);
      -v /srv/newsblur:/srv/newsblur
      --network=newsblurnet
      --hostname {{ ansible_hostname }} 
      newsblur/newsblur_python3 /srv/newsblur/utils/monitor_disk_usage.py $OUTPUT
  tags:
    - sanity-checker
