---
# - name: Remove old .deb
#   become: yes
#   file:
#     path: /home/nb/sysbench.deb.sh
#     state: absent

- name: Download sysbench and prepare .deb
  get_url:
    url: https://packagecloud.io/install/repositories/akopytov/sysbench/script.deb.sh
    dest: /home/nb/sysbench.deb.sh

- name: Prepare .deb
  become: yes
  command: bash /home/nb/sysbench.deb.sh

- name: Apt install sysbench
  become: yes
  apt:
    package: sysbench
    state: latest

- name: Run sysbench CPU
  shell:
    # chdir: "/mnt/{{ inventory_hostname|regex_replace('db-', '')|regex_replace('-', '') }}"
    cmd: sysbench cpu --cpu-max-prime=20000 run
  register: cpu

- name: Benchmark cpu results
  debug: msg="{{ cpu.stdout.split('\n') }}"

- name: Prepare sysbench disk i/o 
  become: yes
  shell:
    # chdir: "/mnt/{{ inventory_hostname|regex_replace('db-', '')|regex_replace('-', '') }}"
    cmd: sysbench fileio --file-total-size=150G prepare
  
- name: Run sysbench disk i/o
  become: yes
  shell:
    # chdir: "/mnt/{{ inventory_hostname|regex_replace('db-', '')|regex_replace('-', '') }}"
    cmd: sysbench fileio --file-total-size=150G --file-test-mode=rndrw --time=300 --max-requests=0 run
  register: io
  
- name: Cleanup sysbench
  become: yes
  shell:
    # chdir: "/mnt/{{ inventory_hostname|regex_replace('db-', '')|regex_replace('-', '') }}"
    cmd: sysbench fileio --file-total-size=150G cleanup

- name: Benchmark io results
  debug: msg="{{ io.stdout.split('\n') }}"
