---
- name: DEPLOY -> staging
  hosts: staging
  gather_facts: false
  vars_files:
    - ../env_vars/base.yml

  tasks:
    - name: Pull newsblur_web github
      git:
        repo: https://github.com/samuelclay/NewsBlur.git
        dest: /srv/newsblur/
        version: master
      register: pulled
    
    - name: Reload gunicorn
      become: yes
      command: "docker kill --signal=HUP newsblur_web"
      # when: pulled.changed

    - name: Update Sentry release
      shell: >
        curl {{ sentry_web_release_webhook }}/ \
        -X POST \
        -H 'Content-Type: application/json' \
        -d '{"version": "{{ lookup('pipe', 'date "+%Y-%m-%d %H:%M:%S"') }}"}'
