---
- name: SETUP -> metrics containers
  hosts: metrics
  vars_files:
    - ../env_vars/base.yml
  vars:
    - update_apt_cache: yes
    - motd_role: db

  roles:
    - {role: 'base', tags: 'base'}
    - {role: 'ufw', tags: 'ufw'}
    - {role: 'docker', tags: 'docker'}
    - {role: 'repo', tags: 'repo'}
    - {role: 'dnsmasq', tags: 'dnsmasq'}
    - {role: 'consul', tags: 'consul'}
    - {role: 'consul-client', tags: 'consul'}

    - {role: 'node-exporter', tags: ['node-exporter', 'metrics']}
    - {role: 'prometheus', tags: ['prometheus', 'metrics']}
    - {role: 'grafana', tags: ['grafana', 'metrics']}
