---
- name: SETUP -> staging containers
  hosts: staging
  vars_files:
    - ../env_vars/base.yml
  vars:
    - update_apt_cache: yes
    - motd_role: app
    # - disable_consul_services: yes # Defined in group vars

  roles:
    - {role: 'base', tags: 'base'}
    - {role: 'ufw', tags: 'ufw'}
    - {role: 'docker', tags: 'docker'}
    - {role: 'repo', tags: 'repo'}
    - {role: 'dnsmasq', tags: 'dnsmasq'}
    - {role: 'consul', tags: 'consul'}
    - {role: 'consul-client', tags: 'consul'}

    - {role: 'letsencrypt', tags: 'letsencrypt'}
    - {role: 'haproxy', tags: 'haproxy'}
    - {role: 'web', tags: 'web'}
    - {role: 'nginx', tags: 'nginx'}
    - {role: 'node', tags: 'node'}
    - {role: 'prometheus', tags: 'prometheus'}
    - {role: 'node-exporter', tags: 'node-exporter'}
    - {role: 'grafana', tags: 'grafana'}
