---
- name: SETUP -> consul manager containers
  hosts: consul
  vars:
    - update_apt_cache: yes
    - motd_role: db
  vars_files:
    - ../env_vars/base.yml
    
  roles:
    - {role: 'base', tags: 'base'}
    - {role: 'ufw', tags: 'ufw'}
    - {role: 'docker', tags: 'docker'}
    - {role: 'repo', tags: ['repo', 'pull']}
    - {role: 'dnsmasq', tags: 'dnsmasq'}
    - {role: 'consul', tags: 'consul'}
    - {role: 'consul-manager', tags: 'consul'}
    - {role: 'node-exporter', tags: ['node-exporter', 'metrics']}
