---

- name: Template file for prometheus
  vars:
    monitor_server: "{{ 'staging.newsblur.com' if disable_consul_services_ie_staging is defined else 'newsblur.com' }}"
  template:
    src: /srv/newsblur/docker/prometheus/prometheus.consul.yml.j2
    dest: /srv/newsblur/docker/prometheus/prometheus.yml
  notify:
    - restart prometheus

- name: Register prometheus in consul
  tags: consul
  become: yes
  template:
    src: consul_service.json
    dest: /etc/consul.d/prometheus.json
  notify:
    - reload consul
  when: disable_consul_services_ie_staging is not defined

- name: Start prometheus docker container
  become: yes
  docker_container:
    name: prometheus
    image: prom/prometheus
    user: root
    networks_cli_compatible: yes
    network_mode: default
    command: --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus --storage.tsdb.retention.time=10y
    networks:
      - name: newsblurnet
    state: started
    ports:
    - 9090:9090
    restart_policy: unless-stopped
    container_default_behavior: no_defaults
    volumes:
      - /srv/newsblur/docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - /mnt/metrics/prometheus_data:/prometheus
