
- name: Start mongo-exporter container
  become: yes
  docker_container:
    name: mongo-exporter
    image: bitnami/mongodb-exporter
    restart_policy: unless-stopped
    container_default_behavior: no_defaults
    networks_cli_compatible: yes
    network_mode: default
    networks:
      - name: newsblurnet
    env:
      # MONGODB_URI: 'mongodb://{{ inventory_hostname }}.node.nyc1.consul:27017/admin?'
      MONGODB_URI: 'mongodb://{{ mongodb_username }}:{{ mongodb_password }}@{{ inventory_hostname }}.node.nyc1.consul:27017/admin?authSource=admin'
    ports:
    - '9216:9216'

- name: Register mongo-exporter in consul
  tags: consul
  become: yes
  template:
    src: consul_service.json
    dest: /etc/consul.d/mongo-exporter.json
  notify:
    - reload consul
- name: Command to register mongo-exporter
  command: "consul services register /etc/consul.d/mongo-exporter.json"
