global:
    scrape_interval: 30s
    external_labels:
        monitor: 'my-monitor'

rule_files:
  - "/etc/prometheus/prometheus_rules.yml"

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

scrape_configs:
    - job_name: 'node-exporter'
      static_configs:
        - targets: ['node-exporter:9100']

    - job_name: 'app_servers'
      static_configs:
        - targets: ['haproxy']
      metrics_path: /monitor/app-servers
      scheme: https
      tls_config:
        insecure_skip_verify: true
    - job_name: 'app_times'
      static_configs:
        - targets: ['haproxy']
      metrics_path: /monitor/app-times
      scheme: https
      tls_config:
        insecure_skip_verify: true
    - job_name: 'classifiers'
      static_configs:
        - targets: ['haproxy']
      metrics_path: /monitor/classifiers
      scheme: https
      tls_config:
        insecure_skip_verify: true
    - job_name: 'db_times'
      static_configs:
        - targets: ['haproxy']
      metrics_path: /monitor/db-times
      scheme: https
      tls_config:
        insecure_skip_verify: true
    - job_name: 'errors'
      static_configs:
        - targets: ['haproxy']
      metrics_path: /monitor/errors
      scheme: https
      tls_config:
        insecure_skip_verify: true
    - job_name: 'feed_sizes'
      static_configs:
        - targets: ['haproxy']
      metrics_path: /monitor/feed-szies
      scheme: https
      tls_config:
        insecure_skip_verify: true
    - job_name: 'feed_counts'
      static_configs:
        - targets: ['haproxy']
      metrics_path: /monitor/feed-counts
      scheme: https
      tls_config:
        insecure_skip_verify: true
    - job_name: 'feeds'
      static_configs:
        - targets: ['haproxy']
      metrics_path: /monitor/feeds
      scheme: https
      tls_config:
        insecure_skip_verify: true
    - job_name: 'load_times'
      static_configs:
        - targets: ['haproxy']
      metrics_path: /monitor/load-times
      scheme: https
      tls_config:
        insecure_skip_verify: true
    - job_name: 'stories'
      static_configs:
        - targets: ['haproxy']
      metrics_path: /monitor/stories
      scheme: https
      tls_config:
        insecure_skip_verify: true
    - job_name: 'task_codes'
      static_configs:
        - targets: ['haproxy']
      metrics_path: /monitor/task-codes
      scheme: https
      tls_config:
        insecure_skip_verify: true
    - job_name: 'task_pipeline'
      static_configs:
        - targets: ['haproxy']
      metrics_path: /monitor/task-pipeline
      scheme: https
      tls_config:
        insecure_skip_verify: true
    - job_name: 'task_servers'
      static_configs:
        - targets: ['haproxy']
      metrics_path: /monitor/task-servers
      scheme: https
      tls_config:
        insecure_skip_verify: true
    - job_name: 'task_times'
      static_configs:
        - targets: ['haproxy']
      metrics_path: /monitor/task-times
      scheme: https
      tls_config:
        insecure_skip_verify: true
    - job_name: 'updates'
      static_configs:
        - targets: ['haproxy']
      metrics_path: /monitor/updates
      scheme: https
      tls_config:
        insecure_skip_verify: true
    - job_name: 'users'
      static_configs:
        - targets: ['haproxy']
      metrics_path: /monitor/users
      scheme: https
      tls_config:
        insecure_skip_verify: true
    - job_name: 'django'
      static_configs:
        - targets: ['haproxy']
      metrics_path: /metrics
      scheme: https
      tls_config:
        insecure_skip_verify: true

    #- job_name: 'mongo heap usage'
    #  static_configs:
    #    - targets: ['flask_metrics:5569']
    #  metrics_path: /mongo/heap-usage
    #  scheme: http
    #  tls_config:
    #    insecure_skip_verify: true
    - job_name: 'mongo objects'
      static_configs:
        - targets: ['flask_metrics_mongo:5569']
      metrics_path: /objects/
      scheme: http
      tls_config:
        insecure_skip_verify: true
    - job_name: 'mongo repl set lag'
      static_configs:
        - targets: ['flask_metrics_mongo:5569']
      metrics_path: /repl-set-lag/
      scheme: http
      tls_config:
        insecure_skip_verify: true
    - job_name: 'mongo size'
      static_configs:
        - targets: ['flask_metrics_mongo:5569']
      metrics_path: /size/
      scheme: http
      tls_config:
        insecure_skip_verify: true
    - job_name: 'mongo ops'
      static_configs:
        - targets: ['flask_metrics_mongo:5569']
      metrics_path: /ops/
      scheme: http
      tls_config:
        insecure_skip_verify: true
    - job_name: 'mongo page faults'
      static_configs:
        - targets: ['flask_metrics_mongo:5569']
      metrics_path: /page-faults/
      scheme: http
      tls_config:
        insecure_skip_verify: true
    - job_name: 'mongo page queues'
      static_configs:
        - targets: ['flask_metrics_mongo:5569']
      metrics_path: /page-queues/
      scheme: http
      tls_config:
        insecure_skip_verify: true

    - job_name: 'redis active connections'
      static_configs:
        - targets: ['flask_metrics_redis:5589']
      metrics_path: /active-connections/
      scheme: http
      tls_config:
        insecure_skip_verify: true
    - job_name: 'redis commands'
      static_configs:
        - targets: ['flask_metrics_redis:5589']
      metrics_path: /commands/
      scheme: http
      tls_config:
        insecure_skip_verify: true
    - job_name: 'redis connects'
      static_configs:
        - targets: ['flask_metrics_redis:5589']
      metrics_path: /connects/
      scheme: http
      tls_config:
        insecure_skip_verify: true
    - job_name: 'redis size'
      static_configs:
        - targets: ['flask_metrics_redis:5589']
      metrics_path: /size/
      scheme: http
      tls_config:
        insecure_skip_verify: true
    - job_name: 'redis memory'
      static_configs:
        - targets: ['flask_metrics_redis:5589']
      metrics_path: /memory/
      scheme: http
      tls_config:
        insecure_skip_verify: true
    - job_name: 'redis used memory'
      static_configs:
        - targets: ['flask_metrics_redis:5589']
      metrics_path: /used-memory/
      scheme: http
      tls_config:
        insecure_skip_verify: true

    - job_name: 'elastic search exporter'
      static_configs:
        - targets: ['elasticsearch_exporter:9114']
      scheme: http
      tls_config:
        insecure_skip_verify: true

    - job_name: 'postgres exporter'
      static_configs:
        - targets: ['postgres_exporter:9187']
      scheme: http
      tls_config:
        insecure_skip_verify: true

    - job_name: 'haproxy state'
      static_configs:
        - targets: ['flask_metrics_haproxy:5599']
      metrics_path: /state/
      scheme: http
      tls_config:
        insecure_skip_verify: true
      scrape_interval: 30s
