global:
    scrape_interval: 5s
    external_labels:
        monitor: 'my-monitor'

rule_files:
  - "/etc/prometheus/prometheus_rules.yml"

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

scrape_configs:
    - job_name: 'node-exporter'
      static_configs:
        - targets: ['node-exporter:9100']

    - job_name: 'app_servers'
      static_configs:
        - targets: ['haproxy']
      metrics_path: /monitor/app-servers
      scheme: https
      tls_config:
        insecure_skip_verify: true
    - job_name: 'app_times'
      static_configs:
        - targets: ['haproxy']
      metrics_path: /monitor/app-times
      scheme: https
      tls_config:
        insecure_skip_verify: true
    - job_name: 'classifiers'
      static_configs:
        - targets: ['haproxy']
      metrics_path: /monitor/classifiers
      scheme: https
      tls_config:
        insecure_skip_verify: true
    - job_name: 'db_times'
      static_configs:
        - targets: ['haproxy']
      metrics_path: /monitor/db-times
      scheme: https
      tls_config:
        insecure_skip_verify: true
    - job_name: 'errors'
      static_configs:
        - targets: ['haproxy']
      metrics_path: /monitor/errors
      scheme: https
      tls_config:
        insecure_skip_verify: true
    - job_name: 'feed_counts'
      static_configs:
        - targets: ['haproxy']
      metrics_path: /monitor/feed-counts
      scheme: https
      tls_config:
        insecure_skip_verify: true
    - job_name: 'feeds'
      static_configs:
        - targets: ['haproxy']
      metrics_path: /monitor/feeds
      scheme: https
      tls_config:
        insecure_skip_verify: true
    - job_name: 'load_times'
      static_configs:
        - targets: ['haproxy']
      metrics_path: /monitor/load-times
      scheme: https
      tls_config:
        insecure_skip_verify: true
    - job_name: 'stories'
      static_configs:
        - targets: ['haproxy']
      metrics_path: /monitor/stories
      scheme: https
      tls_config:
        insecure_skip_verify: true
    - job_name: 'task_codes'
      static_configs:
        - targets: ['haproxy']
      metrics_path: /monitor/task-codes
      scheme: https
      tls_config:
        insecure_skip_verify: true
    - job_name: 'task_pipeline'
      static_configs:
        - targets: ['haproxy']
      metrics_path: /monitor/task-pipeline
      scheme: https
      tls_config:
        insecure_skip_verify: true
    - job_name: 'task_servers'
      static_configs:
        - targets: ['haproxy']
      metrics_path: /monitor/task-servers
      scheme: https
      tls_config:
        insecure_skip_verify: true
    - job_name: 'task_times'
      static_configs:
        - targets: ['haproxy']
      metrics_path: /monitor/task-times
      scheme: https
      tls_config:
        insecure_skip_verify: true
    - job_name: 'updates'
      static_configs:
        - targets: ['haproxy']
      metrics_path: /monitor/updates
      scheme: https
      tls_config:
        insecure_skip_verify: true
    - job_name: 'users'
      static_configs:
        - targets: ['haproxy']
      metrics_path: /monitor/users
      scheme: https
      tls_config:
        insecure_skip_verify: true

    - job_name: 'mongo heap usage'
      static_configs:
        - targets: ['haproxy']
      metrics_path: /monitor/mongo-heap-usage
      scheme: https
      tls_config:
        insecure_skip_verify: true
    - job_name: 'mongo objects'
      static_configs:
        - targets: ['haproxy']
      metrics_path: /monitor/mongo-objects
      scheme: https
      tls_config:
        insecure_skip_verify: true
    - job_name: 'mongo repl set lag'
      static_configs:
        - targets: ['haproxy']
      metrics_path: /monitor/mongo-replset-lag
      scheme: https
      tls_config:
        insecure_skip_verify: true
    - job_name: 'mongo size'
      static_configs:
        - targets: ['haproxy']
      metrics_path: /monitor/mongo-size
      scheme: https
      tls_config:
        insecure_skip_verify: true
    - job_name: 'mongo ops'
      static_configs:
        - targets: ['haproxy']
      metrics_path: /monitor/mongo-ops
      scheme: https
      tls_config:
        insecure_skip_verify: true
    - job_name: 'mongo page faults'
      static_configs:
        - targets: ['haproxy']
      metrics_path: /monitor/mongo-page-faults
      scheme: https
      tls_config:
        insecure_skip_verify: true
    - job_name: 'mongo page queues'
      static_configs:
        - targets: ['haproxy']
      metrics_path: /monitor/mongo-page-queues
      scheme: https
      tls_config:
        insecure_skip_verify: true
