# Use this playbook to run a tag on every server. Handy for firewalls.

---
- hosts: all
  # strategy: free
  vars_files:
    - env_vars/base.yml
  vars:
    - update_apt_cache: yes
  roles:
    - {role: 'base', tags: 'base'}
    - {role: 'ufw', tags: 'ufw'}
    - {role: 'docker', tags: 'docker'}
    - {role: 'repo', tags: ['repo', 'pull']}
    - {role: 'dnsmasq', tags: 'dnsmasq'}
    - {role: 'consul', tags: 'consul'}
    - {role: 'consul-client', tags: 'consul'}
    - {role: 'monitor', tags: 'monitor'}
