---
- hosts: work
  gather_facts: false
  vars_files:
    - env_vars/base.yml
    - env_vars/dev.yml

  tasks:
    - name: Pull newsblur_web github
      git:
        repo: https://github.com/samuelclay/NewsBlur.git
        dest: /srv/newsblur/
        version: dashboard3
      register: pulled
    
    - name: Reload celery
      become: yes
      command: "docker kill --signal=HUP task-work"
      when: '"task-work" in inventory_hostname'
