---
- import_playbook: setup_app.yml
  when: "'app' in group_names"
- import_playbook: setup_www.yml
  when: "'haproxy' in group_names"
- import_playbook: setup_node.yml
  when: "'node' in group_names"
- import_playbook: setup_postgres.yml
  when: "'postgres' in group_names"
- import_playbook: setup_mongo.yml
  when: "'mongo' in group_names"
- import_playbook: setup_redis.yml
  when: "'redis' in group_names"
- import_playbook: setup_elasticsearch.yml
  when: "'elasticsearch' in group_names"
- import_playbook: setup_task.yml
  when: "'task' in group_names"
# - import_playbook: setup_debug.yml
#   when: "'debugs' in group_names"
- import_playbook: setup_consul_manager.yml
  when: "'consul' in group_names"
