---
- name: SETUP -> www containers
  hosts: www
  vars:
    - update_apt_cache: yes
    - motd_role: app
  vars_files:
    - env_vars/base.yml
    
  roles:
    - {role: 'base', tags: 'base'}
    - {role: 'docker', tags: 'docker'}
    - {role: 'repo', tags: 'repo'}
    - {role: 'dnsmasq', tags: 'consul'}
    - {role: 'consul', tags: 'consul'}
    - {role: 'consul-client', tags: 'consul'}
    - {role: 'monitor', tags: 'monitor'}
    - {role: 'letsencrypt', tags: 'letsencrypt'}
    - {role: 'haproxy', tags: 'haproxy'}
