---
- name: SETUP -> consul manager containers
  hosts: db-consul
  vars:
    - update_apt_cache: yes
    - motd_role: db
  vars_files:
    - env_vars/base.yml
    
  roles:
    - {role: 'base', tags: 'base'}
    - {role: 'docker', tags: 'docker'}
    - {role: 'repo', tags: 'repo'}
    - {role: 'consul', tags: 'consul'}
    - {role: 'consul-manager', tags: 'consul'}
