---
- name: SETUP -> elasticsearch containers
  hosts: elasticsearch
  vars:
    - update_apt_cache: yes
    - motd_role: db
  vars_files:
    - env_vars/base.yml
  roles:
    - {role: 'base', tags: 'base'}
    - {role: 'docker', tags: 'docker'}
    - {role: 'repo', tags: 'repo'}
    - {role: 'dnsmasq', tags: 'consul'}
    - {role: 'consul', tags: 'consul'}
    - {role: 'consul-client', tags: 'consul'}
    - {role: 'elasticsearch', tags: 'elasticsearch'}
